### ISSUE TITLE
System for Active cup

### ISSUE THREAD

**Issue by skybaks** [skybaks/pyplanet-cup_manager#28]
Maybe add commands like `//cup start` and `//cup end` that would cause matches inbetween to be added to `//cup results`.
Then print cup top 10 standings at the end of each map like in smurfscup

**Comment by rocheGit** [comment]
It would be great to add the possibility to store long term all the cup results saved with this method somewhere on the server, to be able to pull a file where we could do some global cup stats in a spreadsheet software from time to time (for eg. to see the average position of every one in all the cups, total number of editions driven by person and other fun stats)

**Comment by skybaks** [comment]
I think what we could do for that is perhaps create an interface that would allow you to mark certain matches in the match history to be saved permanently. I'll have to think more about how much stats logic I want to implement on the plugin side and how much I intend to offload to you via use of the csv export ;)

**Comment by rocheGit** [comment]
Sure, an interface would work well too (or i can continue doing the csv export manually, it's just if I can save myself the effort of having to look for and open my .csv at every cup i'll take it)

I like the idea of linking it to the //cup start command because it means it could be automatically saved for other cups where admin don't care so much about this, and in the long term if someone wants to do stats the data would already be here (it's basically impossible to do stats by scraping the discord results, as logins aren't on them)

**Comment by skybaks** [comment]
All good points. I'll think on it and see what I can come up with.
