### ISSUE TITLE
Export data directly to clipboard

### ISSUE THREAD

**Issue by reaby** [skybaks/pyplanet-cup_manager#65]
I have issue with the textedit fields, it doesn't keep newlines... 
Would it be possible for you to automatically export the data to clipboard without ctrl-a ctrl-c from textfield ?
You can do this easily with templateview and a small maniascript:

```ts
<script><!--
  main() {
  System.ClipboardSet("""{{ str_data }}""");
  }
--></script>
```

also google sheets export would be nice: it uses simple tab as column separator and newline as line separator
example:
```python 
for range(x,x):
strdata += f"{value1}\t{value2}\n"
```

**Comment by skybaks** [comment]
> Would it be possible for you to automatically export the data to clipboard without ctrl-a ctrl-c from textfield ?

![image](https://github.com/skybaks/pyplanet-cup_manager/assets/52106022/287f2356-d173-4cdb-b4f9-ce303f62f1d9)
Yes, it is possible! There is a button under the displayed textbox on the export window that will copy the text into your clipboard.

> also google sheets export would be nice

For Google sheets, there is already a csv export option (also shown in the screenshot above). It is comma delimited instead of tab delimited but last time I tested sheets seemed to be OK with that.

**Comment by skybaks** [comment]
I added an icon to the "Copy Text" button in https://github.com/skybaks/pyplanet-cup_manager/commit/93efd2ebc4db78058ff29c0940a191b46190b5ef
Hopefully this helps to illuminate the button.
